<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_10 YouTube Marketing Strategies That Make Me 6-Figures</name>
   <tag></tag>
   <elementGuidId>95970af2-31f2-443b-8d70-8cb562be5f5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/main/div/div/div/div/div[2]/div/div/div[2]/div/div/div[9]/div/div[2]/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cs-list-ellipsis-title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10 YouTube Marketing Strategies That Make Me 6-Figures</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app bg-gray-main&quot;]/div[@class=&quot;min-height-65vh m-0 row&quot;]/div[@class=&quot;pl-0 pr-0 col-12 col-sm-12 col-md-9 col-lg-9&quot;]/main[1]/div[1]/div[@class=&quot;animated fadeIn main container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-12 col-lg-12&quot;]/div[@class=&quot;card-custom card&quot;]/div[@class=&quot;card-custom body white card-body&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-12 col-lg-12&quot;]/div[@class=&quot;data-container&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-4 col-lg-4&quot;]/div[@class=&quot;cs-list-col-wrapper col&quot;]/div[@class=&quot;cs-list-wrapper bottom row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;pt-1 pl-3 row&quot;]/div[@class=&quot;cs-list-ellipsis-title&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/main/div/div/div/div/div[2]/div/div/div[2]/div/div/div[9]/div/div[2]/div/div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Marketing'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit'])[8]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Categorized'])[9]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/div/div[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
